name: project-APIGEE-Target-Servers-Pipeline
run-name: ${{ github.triggering_actor }} ran pipeline for APIGEE Target Servers deployment.
on:
  workflow_call:
    inputs:
      apigee-environment:
        type: string
        required: true
        description: 'To Get APIGEE environment to deploy proxy'
jobs:
  Notify_On_Slack_for_approval:
    uses: ./.github/workflows/Notify-On-Slack.yml
    with:
      workflow_status: Awaiting for Reviewer Approval
    secrets: inherit
  
  Dev_Deployment_worflow:
    needs: Notify_On_Slack_for_approval
    if: inputs.apigee-environment == 'development'
    uses: ./.github/workflows/Target-Servers-Deploy.yml
    with:
      apigee-environment: development
    secrets: inherit    

  Stagging_Deployment_worflow:
    needs: Notify_On_Slack_for_approval
    if: inputs.apigee-environment == 'staging'
    uses: ./.github/workflows/Target-Servers-Deploy.yml
    with:
      apigee-environment: staging
    secrets: inherit

  Production_Deployment_worflow:
    needs: Notify_On_Slack_for_approval
    if: inputs.apigee-environment == 'production'
    uses: ./.github/workflows/Target-Servers-Deploy.yml
    with:
      apigee-environment: production
    secrets: inherit
  
  Notify_Workflow_Status_On_Slack:
    if: always()
    needs: [Stagging_Deployment_worflow, Production_Deployment_worflow, Dev_Deployment_worflow ]
    uses: ./.github/workflows/Notify-On-Slack.yml
    with:
      workflow_status: ${{needs.Dev_Deployment_worflow.outputs.step-status}}${{needs.Production_Deployment_worflow.outputs.step-status}}${{ needs.Stagging_Deployment_worflow.outputs.step-status }}
    secrets: inherit